### ISSUE TITLE
#saver should ignore unsupported options

### ISSUE THREAD

**Issue by mokolabs** [janko-m/image_processing#17] opened 2018-03-20 17:54 UTC
So I'm using the saver method to set the quality level of my JPEGs in my Shrine app.

```ruby
ImageProcessing::Vips
  .source(image)
  .autorot
  .resize_to_fit, 1024, 1024)
  .saver(Q: 85, interlace: true)
  .sharpen(sigma: 1.5, x1: 1.5, y2: 15, y3: 15, m1: 0.4, m2: 0.8)
  .call
```

The app itself is agnostic about supported image file types. You can upload a JPEG, PNG, or GIF. But when I run a PNG or GIF through my version processor in Shrine, I get this error:

`Vips::Error: unable to call VipsForeignSavePngFile: unknown option Q`

It would be better to discard unsupported options when #saver arguments get passed along to #vips_pngsave, etc.

That way, it would just do the right thing with each respective image format -- without any errors.

**Comment by janko-m** [comment] 2018-03-20 18:01
Yeah, that makes sense. The problem is that I currently don't know how to programatically determine which options are supported and which aren't. The `ruby-vips` gem might have a libvips function exposed for this, I'll take a look.

**Comment by mokolabs** [comment] 2018-03-20 18:10
Yeah, as far as i know, Q and interlace are JPEG-only options.

Q being the JPEG quality setting, of course, and setting interlace to true will generate a JPEG which renders progressively.

You could start just with those two -- so they aren't useful when saving to GIF and PNG, and are causing errors when included.

And then maybe add support for other options later.

**Comment by mokolabs** [comment] 2018-03-20 18:19
Also... I just realized that libvips maybe doesn't support writing GIFs at all?

I got this error when processing a GIF upload:

`Vips::Error: No known saver for '/var/folders/l8/6byfsg9s46vggvdx3g9r5ktw0000gn/T/image_processing-vips20180320-53928-1sge9i2.gif'.`

**Comment by janko-m** [comment] 2018-03-20 18:25
@mokolabs Yes, that's correct, libvips doesn't have a GIF saver. I'm ok with an exception being raised in this case, because the user should decide how they want to handle this case (I don't see a good default, as GIF is a multilayer format).

**Comment by mokolabs** [comment] 2018-03-20 18:47
Yeah, I did a bit more digging and I also discovered that libvps doesn't support 8-bit PNGs:
https://github.com/jcupitt/libvips/issues/734

In my case, I've got a large photo library with 200K images, so I can't retroactively remove GIF support. I considered just converting these GIFs into PNGs, but libvips doesn't support 8-bit PNGs -- only 24-bit PNGs.

So, when I tried converting a GIF upload into a 24-bit PNG, the total file size of all the generated versions grew from 3.9 MB to 25.4 MB. So that's not a viable option for me.

However, in my case, the speed increase of libvips for JPEGs and PNGs is so great, I'm leaning towards using a dual libvps / minimagick implementation in my uploader (where I keep minimagick around only for GIF support).

But, if people need GIF support and speed isn't critical, they should probably just use minimagick. We should also probably mention some of these libvips limitations in the README, just so folks know before they pick an implementation.

**Comment by janko-m** [comment] 2018-03-20 18:47
> You could start just with those two -- so they aren't useful when saving to GIF and PNG, and are causing errors when included.
> 
> And then maybe add support for other options later.

I don't find this ideal, as then we'd have to update the code if other lossy formats gain these saver options too.

What do you think about adding the ability to define format-specific saver options, which will only be applied for matching destination formats?

```rb
ImageProcessing::Vips
  .source(image)
  .autorot
  .resize_to_fit, 1024, 1024)
  .saver(jpeg: { Q: 85, interlace: true }, png: { compression: 2 })
  .sharpen(sigma: 1.5, x1: 1.5, y2: 15, y3: 15, m1: 0.4, m2: 0.8)
  .call
```

**Comment by janko-m** [comment] 2018-03-20 18:56
> I considered just converting these GIFs into PNGs, but libvips doesn't support 8-bit PNGs -- only 24-bit PNGs.

Hmm, the [`vips_pngsave()`](http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-pngsave) documentation mentions 8-bit PNGs 🤔 

There also seems to be a `magicksave` saver in progress, which should allow you to do an "ImageMagick save" using libvips – https://github.com/jcupitt/libvips/issues/839

> We should also probably mention some of these libvips limitations in the README, just so folks know before they pick an implementation.

I agree, it would be good to mention these limitations 👍

**Comment by janko-m** [comment] 2018-03-20 19:28
> What do you think about adding the ability to define format-specific saver options, which will only be applied for matching destination formats?

Hmm, that's not ideal, as TIFF and WEBP savers also support the `:Q` option, and PNG saver also supports the `:interlace` option, so if one wanted to apply these options to all the supported output formats, it would require code duplication and research.

I will try going with your suggestion instead. `ruby-vips` does have the ability to dynamically introspect operation arguments, it's just not an easy-to-use API.

**Comment by janko-m** [comment] 2018-03-20 20:08
@mokolabs I just pushed https://github.com/janko-m/image_processing/commit/b08ceefffd2da46915778f3aabd0a1c41b153aa9, which should make undefined saver options be automatically ignored. Could you check whether your code works with this change?

**Comment by mokolabs** [comment] 2018-03-21 00:19
Yes, that worked. I was able to process both JPEGs and PNGs with the same options.

Two observations:

- The PNG upload worked, but with this warning:
  `VIPS-WARNING **: 17:10:19.595: Interlace handling should be turned on when using png_read_image`

- I tried a GIF upload just to see what happens. With the code from master, I get this error: 'ArgumentError: Must supply a pointer to memory for the Struct'. The error message from 0.9.0 is different, though: `Vips::Error: No known saver for '/var/folders/l8/6byfsg9s46vggvdx3g9r5ktw0000gn/T/image_processing-vips20180320-42548-66179f.gif'.` I didn't expect it to work, but it's interesting that your changes yielded a different error.

**Comment by janko-m** [comment] 2018-03-21 01:14
@mokolabs Thanks for reporting, that was a bug in the new change, I just pushed https://github.com/janko-m/image_processing/commit/d47458be58a3b2b189dc52ddfe0daf0cc1417e25 that should bring back the correct error message.

**Comment by janko-m** [comment] 2018-03-21 01:20
I don't know what causes the PNG warning, though 🤷‍♂️

**Comment by mokolabs** [comment] 2018-03-21 15:13
Yeah, looks like that warning is bubbling up from libpng:

https://sourceforge.net/p/libpng/bugs/165/

It appears to be a long-standing issue in libpng that is unlikely to be fixed at a fundamental level.

**Comment by mokolabs** [comment] 2018-03-21 15:57
Just tested d47458be58a3b2b189dc52ddfe0daf0cc1417e25 and I can confirm that attempting to process a GIF upload once again results in the correct error:

`WARN: Vips::Error: No known saver for '/var/folders/l8/6byfsg9s46vggvdx3g9r5ktw0000gn/T/image_processing20180321-93162-1lqcqbw.gif'.`

**Comment by mokolabs** [comment] 2018-03-21 16:08
FYI... after more research, I discovered that all three image formats (JPG, PNG, GIF) technically support interlacing.

minimagick (and imagemagick) supports interlacing all three formats. libvips supports interlacing on JPEGs and PNGs (but not GIFs -- since libvips can't write GIFs).

**Comment by janko-m** [comment] 2018-03-21 21:48
Closing this now, feel free to reopen if there is anything else you think needs to be modified in the implementation regarding saver/loader options.

**Closed by janko-m** 2018-03-21 21:48 UTC
